import os

AT_SPEECH_DIR = os.path.abspath(os.path.dirname(__file__))
TR34_PRETRAIN_PATH = os.path.join(AT_SPEECH_DIR, "pretrained_models/thin_resnet34.h5")

FEAT_KAPRE_MELSPECGRAM = "FEAT_KAPRE_MELSPECGRAM"
FEAT_LBS_MELSPECGRAM = "FEAT_LBS_MELSPECGRAM"
FEAT_LBS_TR34 = "FEAT_LBS_TR34"

CLS_LR_LIBLINEAER = "LR_LIBLINEAR_CLS"
CLS_LR_SAG = "LR_SAG_CLS"
CLS_TR34 = "TR34_CLS"

