NUMERICAL_TYPE = "num"
NUMERICAL_PREFIX = "n_"

CATEGORY_TYPE = "cat"
CATEGORY_PREFIX = "c_"

TIME_TYPE = "time"
TIME_PREFIX = "t_"

MULTI_CAT_TYPE = "multi-cat"
MULTI_CAT_PREFIX = "m_"
MULTI_CAT_DELIMITER = ","

VECTOR_TYPE = 'vec'
VECTOR_PREFIX = 'v_'


BINARY_TYPE = "binary"
BINARY_PREFIX = 'b_'

MAIN_TABLE_NAME = "main"
MAIN_TABLE_TEST_NAME = "main_test"
TABLE_PREFIX = "table_"

LABEL = "label"

type2prefix = {
    NUMERICAL_TYPE:NUMERICAL_PREFIX,
    CATEGORY_TYPE:CATEGORY_PREFIX,
    TIME_TYPE:TIME_PREFIX,
    MULTI_CAT_TYPE:MULTI_CAT_PREFIX,
    BINARY_TYPE: BINARY_PREFIX
}

JOBS = 4
SEED = 2020

MISSING = -1

